server:
  port: 9090
## DİKKAT!!!!!!
## YML dosyasında bulunan değerleri sistem
## dosyalarından env(Environment Variable)-
## sistem ortam değişkenleri  dan  alabilirsiniz.
spring:
  security:
    user:
      name: muhammet
      password: 1234
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hs2eticaret
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update


logging:
  file:
    name: eticaret.log
  logback:
    rollingpolicy:
      max-file-size: 2MB
  level:
    root: info


benim-uygulamam:
  urun-baslik: 'Yeni Java HS2 '
  default-price: 5000


my-jwt:
  secret-key: "dfvfdgşşl43534646+&/+6534g"
